[package]
name = "async-process"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v1.x.y" git tag
version = "1.2.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async interface for working with processes"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/async-process"
homepage = "https://github.com/smol-rs/async-process"
documentation = "https://docs.rs/async-process"
keywords = ["process", "spawn", "command", "subprocess", "child"]
categories = ["asynchronous", "os"]

[dependencies]
cfg-if = "1.0"
event-listener = "2.4.0"
futures-lite = "1.11.0"
once_cell = "1.4.1"

[target.'cfg(unix)'.dependencies]
async-io = "1.0.0"
libc = "0.2.88"

[target.'cfg(unix)'.dependencies.signal-hook]
version = "0.3.0"
features = ["iterator"]
default-features = false

[target.'cfg(windows)'.dependencies]
blocking = "1.0.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
default-features = false
features = [
  "winbase",
  "winnt"
]
